return {
	{ -- Fuzzy Finder via snacks picker
		"folke/snacks.nvim",
		priority = 1000,
		lazy = false,
		opts = {
			picker = {
				enabled = true,
			},
		},
		keys = {
			{ "<leader><space>", function() Snacks.picker.files() end, desc = "Find files" },
			{ "<leader>fa", function() Snacks.picker.files({ hidden = true }) end, desc = "Find all files" },
			{ "<leader>fo", function() Snacks.picker.recent() end, desc = "Recent files" },
			{ "<leader>fb", function() Snacks.picker.buffers() end, desc = "Buffers" },
			{ "<leader>fg", function() Snacks.picker.grep() end, desc = "Grep" },
			{ "<leader>fw", function() Snacks.picker.grep_word() end, desc = "Grep word", mode = { "n", "x" } },
			{ "<leader>sg", function() Snacks.picker.grep() end, desc = "Search by grep" },
			{ "<leader>sw", function() Snacks.picker.grep_word() end, desc = "Search current word" },
			{ "<leader>sj", function() Snacks.picker.jumps() end, desc = "Jumplist" },
			{ "<leader>sq", function() Snacks.picker.qflist() end, desc = "Quickfix" },
			{ "<leader>ss", function() Snacks.picker.symbols() end, desc = "Symbols" },
			{ "<leader>sm", function() Snacks.picker.marks() end, desc = "Marks" },
			{ "<leader>sh", function() Snacks.picker.help() end, desc = "Help" },
			{ "<leader>sk", function() Snacks.picker.keymaps() end, desc = "Keymaps" },
			{ "<leader>sd", function() Snacks.picker.diagnostics() end, desc = "Diagnostics" },
			{ "<leader>sr", function() Snacks.picker.resume() end, desc = "Resume" },
			{ "<leader>sn", function() Snacks.picker.files({ cwd = vim.fn.stdpath("config") }) end, desc = "Neovim files" },
			{ "<leader>/", function() Snacks.picker.lines() end, desc = "Search in buffer" },
			{ "<localleader>g", function() Snacks.picker.lines() end, desc = "Search in buffer" },
			{ "<leader>wg", function() Snacks.picker.grep({ need_search = false, filter = { cwd = vim.fn.getcwd() } }) end, desc = "Grep open files" },
			{ "<leader>sc", function() Snacks.picker.command_history() end, desc = "Command history" },
			{ "<localleader>c", function() Snacks.picker.commands() end, desc = "Commands" },
			{ "<leader>gf", function() Snacks.picker.git_files() end, desc = "Git files" },
			{ "<leader>th", function() Snacks.picker.colorschemes() end, desc = "Themes" },
		},
	},
}